# Generated by Django 2.1.3 on 2018-11-19 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=30)),
                ('discussion_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('dislike_count', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('pushcontent', models.IntegerField()),
                ('pushdate', models.IntegerField()),
                ('pushauthor', models.IntegerField()),
            ],
        ),
    ]
