# Generated by Django 2.1.3 on 2018-11-19 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pushauthor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='pushcontent',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='pushdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
