# Generated by Django 2.1.3 on 2018-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20181119_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='discussion_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='dislike_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='negative',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='positive',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='pushauthor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='pushcontent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='pushdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='share_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='source',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
