# Generated by Django 2.1.3 on 2018-11-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20181119_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='pushdate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
